Update build-plugins.yml

diff --git a/.github/workflows/build-plugins.yml b/.github/workflows/build-plugins.yml
--- a/.github/workflows/build-plugins.yml
+++ b/.github/workflows/build-plugins.yml
@@ -77,15 +77,31 @@ jobs:
         run: |
           nuget restore Examples/${{ matrix.plugin }}/${{ matrix.plugin }}.sln
 
+      - name: Check files in plugin directory
+        run: |
+          cd Examples/${{ matrix.plugin }}/projects
+          dir
+
       - name: Build VST3 plugin (${{ matrix.plugin }})
         run: |
           cd Examples/${{ matrix.plugin }}/projects
           
-          # Check if the plugin's vst3 project file exists
-          dir
+          # Ensure the props file exists in the expected location
+          if exist "config/IPlugEffect-win.props" (
+            echo "Found the .props file: IPlugEffect-win.props"
+          ) else (
+            echo "Error: .props file not found: IPlugEffect-win.props"
+            exit 1
+          )
 
           # Dynamically build the VST3 plugin using the appropriate .vcxproj file
-          msbuild "${{ matrix.plugin }}-vst3.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:TargetName=VST3
+          if exist "${{ matrix.plugin }}-vst3.vcxproj" (
+            echo "Found the .vcxproj file: ${{ matrix.plugin }}-vst3.vcxproj"
+            msbuild "${{ matrix.plugin }}-vst3.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:TargetName=VST3 /p:VST3_SDK_PATH="${{ github.workspace }}\Dependencies\VST3_SDK"
+          ) else (
+            echo "Error: .vcxproj file not found: ${{ matrix.plugin }}-vst3.vcxproj"
+            exit 1
+          )
 
       - name: Upload VST3 Artifact
         uses: actions/upload-artifact@v4
